# Generated by Django 4.2.7 on 2023-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_platos_procedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(default='ValorPredeterminado', max_length=40),
        ),
    ]
